



title: The Musketeer Mod
description: The Classmod for Gunslingers

#collections:
#  - chapters

collections:
  chapters:
    output: false
  skills:
    output: false
  

# About/contact
author:
  name:       MDZ Kimchi
  url:        https://github.com/wuergrob/Prog1_Uebung_1



github:
  zip_url: http://example.com/download.zip
  another_url: another value

show_downloads: "true"

paginate: 1

theme: jekyll-theme-cayman