theme: jekyll-theme-cayman

title:  Divinity 2 Musketeer Mod
description: A new Classmod for Gunslingers

# About/contact
author:
  name:       MDZ Kimchi
  url:        https://github.com/wuergrob/Prog1_Uebung_1

show_downloads: "true"
